services:
  - type: web
    name: flightclaim-pro
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flightclaim-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
        sync: false

databases:
  - name: flightclaim-db
    databaseName: flightclaim
    user: flightclaim_user
    plan: starter